spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/mr_daebak_dinner?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: mysql1596

  thymeleaf:
    cache: false

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
